server:
  port: 8787

spring:
  main:
    web-application-type: REACTIVE
  data:
    mongodb:
#      username: root
#      password: password
#      host: localhost
#      port: 27017
#      database: db
      uri: mongodb://root:password@localhost:27017/admin
