CREATE TABLE USER
(
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age  INTEGER      NOT NULL
);

CREATE TABLE MESSAGE
(
    id      BIGSERIAL PRIMARY KEY,
    "from"  BIGINT        NOT NULL REFERENCES USER (id),
    "to"    BIGINT        NOT NULL REFERENCES USER (id),
    message VARCHAR(1024) NOT NULL
);

CREATE TABLE LOG
(
    id        BIGSERIAL PRIMARY KEY,
    client    VARCHAR(255) NOT NULL,
    operation VARCHAR(255) NOT NULL,
    entityId  BIGINT       NOT NULL
);
